CREATE TABLE `apartments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`landlordId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`propertyType` enum('apartment','studio','house','room','condo','townhouse') NOT NULL,
	`address` varchar(255) NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(50) NOT NULL,
	`zipCode` varchar(20) NOT NULL,
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`nearbyUniversities` json,
	`distanceToUniversity` decimal(5,2),
	`bedrooms` int NOT NULL,
	`bathrooms` decimal(3,1) NOT NULL,
	`squareFeet` int,
	`floor` int,
	`totalFloors` int,
	`monthlyRent` decimal(10,2) NOT NULL,
	`securityDeposit` decimal(10,2) NOT NULL,
	`applicationFee` decimal(10,2) DEFAULT '0',
	`minLeaseTerm` int DEFAULT 6,
	`maxLeaseTerm` int DEFAULT 12,
	`availableFrom` timestamp NOT NULL,
	`amenities` json,
	`utilitiesIncluded` json,
	`petsAllowed` boolean NOT NULL DEFAULT false,
	`petDeposit` decimal(10,2),
	`petRent` decimal(10,2),
	`parkingIncluded` boolean NOT NULL DEFAULT false,
	`parkingType` enum('garage','covered','street','lot','none'),
	`parkingFee` decimal(10,2),
	`images` json,
	`virtualTourUrl` varchar(500),
	`status` enum('draft','active','pending','rented','inactive') NOT NULL DEFAULT 'draft',
	`featured` boolean NOT NULL DEFAULT false,
	`viewCount` int NOT NULL DEFAULT 0,
	`acceptsInternationalStudents` boolean NOT NULL DEFAULT true,
	`noSsnRequired` boolean NOT NULL DEFAULT true,
	`noCreditCheckRequired` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `apartments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`apartmentId` int NOT NULL,
	`studentId` int NOT NULL,
	`landlordId` int NOT NULL,
	`status` enum('draft','submitted','under_review','documents_requested','approved','rejected','withdrawn','lease_signed','deposit_paid') NOT NULL DEFAULT 'draft',
	`desiredMoveInDate` timestamp NOT NULL,
	`desiredLeaseTerm` int NOT NULL,
	`personalStatement` text,
	`fundingSource` enum('family_support','scholarship','student_loan','personal_savings','employment','combination'),
	`monthlyBudget` decimal(10,2),
	`guarantorAvailable` boolean DEFAULT false,
	`guarantorName` varchar(255),
	`guarantorRelationship` varchar(100),
	`guarantorEmail` varchar(320),
	`guarantorPhone` varchar(30),
	`landlordNotes` text,
	`rejectionReason` text,
	`submittedAt` timestamp,
	`reviewedAt` timestamp,
	`approvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`applicationId` int,
	`documentType` enum('passport','visa','i20','ds2019','enrollment_letter','financial_statement','bank_statement','scholarship_letter','guarantor_letter','proof_of_income','other') NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileKey` varchar(500) NOT NULL,
	`fileUrl` varchar(1000) NOT NULL,
	`mimeType` varchar(100) NOT NULL,
	`fileSize` int NOT NULL,
	`verificationStatus` enum('pending','verified','rejected','expired') NOT NULL DEFAULT 'pending',
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`verificationNotes` text,
	`expirationDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `landlord_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyName` varchar(255),
	`businessType` enum('individual','property_management','real_estate_company'),
	`phoneNumber` varchar(30),
	`businessAddress` text,
	`businessCity` varchar(100),
	`businessState` varchar(50),
	`businessZip` varchar(20),
	`taxId` varchar(50),
	`verified` boolean NOT NULL DEFAULT false,
	`verifiedAt` timestamp,
	`stripeAccountId` varchar(255),
	`stripeOnboardingComplete` boolean NOT NULL DEFAULT false,
	`totalProperties` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `landlord_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `landlord_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`senderId` int NOT NULL,
	`receiverId` int NOT NULL,
	`apartmentId` int,
	`applicationId` int,
	`content` text NOT NULL,
	`read` boolean NOT NULL DEFAULT false,
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `messages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int,
	`apartmentId` int NOT NULL,
	`studentId` int NOT NULL,
	`landlordId` int NOT NULL,
	`paymentType` enum('application_fee','security_deposit','first_month_rent','monthly_rent','pet_deposit','late_fee','other') NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`stripePaymentIntentId` varchar(255),
	`stripeChargeId` varchar(255),
	`stripeTransferId` varchar(255),
	`paymentMethod` varchar(100),
	`status` enum('pending','processing','succeeded','failed','refunded','partially_refunded','cancelled') NOT NULL DEFAULT 'pending',
	`refundAmount` decimal(10,2),
	`refundReason` text,
	`refundedAt` timestamp,
	`description` text,
	`receiptUrl` varchar(500),
	`dueDate` timestamp,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `saved_apartments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`apartmentId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `saved_apartments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `student_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`universityName` varchar(255),
	`universityCity` varchar(100),
	`universityState` varchar(50),
	`programName` varchar(255),
	`expectedGraduation` varchar(20),
	`visaType` enum('F1','J1','M1','H1B','OPT','CPT','other'),
	`visaExpirationDate` timestamp,
	`countryOfOrigin` varchar(100),
	`phoneNumber` varchar(30),
	`emergencyContactName` varchar(255),
	`emergencyContactPhone` varchar(30),
	`profileComplete` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `student_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `student_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `universities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`shortName` varchar(50),
	`city` varchar(100) NOT NULL,
	`state` varchar(50) NOT NULL,
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`internationalStudentCount` int,
	`website` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `universities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin','landlord') NOT NULL DEFAULT 'user';